import { FieldValue, Timestamp } from 'firebase-admin/firestore';
import { assertAdmin, assertBranchAccess, canTrashRecord } from './authz.js';
import { branchLabel, isTrashExpired, trashExpiresAt } from './validators.js';

export async function trashCustomerOperation({ db }, actor, data) { const ref = db.doc(`customers/${data?.id}`); const snapshot = await ref.get(); if (!snapshot.exists) throw new Error('Customer not found'); if (!canTrashRecord(actor, snapshot.data())) throw new Error('Customer trash denied'); const deletedAt=Timestamp.now(); await ref.update({ recordState:'trashed',deletedBy:actor.uid,deletedAt,purgeAfter:Timestamp.fromDate(trashExpiresAt(deletedAt)),updatedBy:actor.uid,updatedAt:FieldValue.serverTimestamp() }); return { id: ref.id, recordState:'trashed' }; }
export async function transferCustomerOperation({ db }, actor, data) { assertAdmin(actor); if (!data?.branchId) throw new Error('Target branch required'); const ref=db.doc(`customers/${data.id}`); const snapshot=await ref.get(); if(!snapshot.exists) throw new Error('Customer not found'); await ref.update({ branchId:data.branchId,branch:branchLabel(data.branchId),updatedBy:actor.uid,updatedAt:FieldValue.serverTimestamp() }); return { id:data.id,branchId:data.branchId }; }
export async function restoreCustomerOperation({ db }, actor, data) { assertAdmin(actor); await db.doc(`customers/${data?.id}`).update({ recordState:'active',deletedBy:null,deletedAt:null,purgeAfter:null,updatedBy:actor.uid,updatedAt:FieldValue.serverTimestamp() }); return { id:data.id }; }

async function deleteManagedImages(bucket, id, customer) { const prefix=`customers/${id}/`; const paths=[customer.imageStoragePath,customer.placeImageStoragePath].filter((path)=>typeof path==='string'&&path.startsWith(prefix)); await Promise.all(paths.map((path)=>bucket.file(path).delete({ ignoreNotFound:true }))); }
export async function permanentlyDeleteCustomerOperation({ db, bucket }, actor, data) { assertAdmin(actor); const ref=db.doc(`customers/${data?.id}`); const snapshot=await ref.get(); if(!snapshot.exists) return { id:data.id,deleted:false }; const customer=snapshot.data(); if(customer.recordState!=='trashed') throw new Error('Only trashed customer can be permanently deleted'); await deleteManagedImages(bucket,ref.id,customer); await ref.delete(); return { id:ref.id,deleted:true }; }
export async function cleanupExpiredCustomers({ db, bucket }, actor, now) { assertAdmin(actor); const snapshots=await db.collection('customers').where('recordState','==','trashed').get(); const expired=snapshots.docs.filter((item)=>isTrashExpired(item.data().deletedAt,now)); for (const item of expired) { assertBranchAccess(actor,item.data().branchId); await deleteManagedImages(bucket,item.id,item.data()); await item.ref.delete(); } return expired.length; }
