import { useEffect, useRef, useState } from 'react';
import { cancelGiftAllocation, confirmGiftAllocation, createGiftAllocation, receiveGiftStock, subscribeActiveGiftItems, subscribeGiftAllocations } from '../services/giftService';
import { giftCallableMessage } from './giftErrors';
import GiftItemRows, { validateGiftItemRows } from './GiftItemRows';
import Button from '../components/ui/Button';
import GlassCard from '../components/ui/GlassCard';
import Input from '../components/ui/Input';
import ModalSheet from '../components/ui/ModalSheet';

const uuid = () => globalThis.crypto.randomUUID();
const actor = (identity) => ({ role: identity?.claims?.role ?? identity?.role, branchId: identity?.claims?.branchId ?? identity?.branchId });
const branchFor = (identity, effective) => actor(identity).role === 'admin' ? effective : actor(identity).branchId;
const firstRow = () => [{ key: 1, giftId: '', packs: '0', looseUnits: '0' }];

export default function GiftInboundPanel({ identity, effectiveBranchId }) {
  const branchId = branchFor(identity, effectiveBranchId); const admin = actor(identity).role === 'admin'; const [catalog, setCatalog] = useState([]); const [allocations, setAllocations] = useState({ pending: [], confirmed: [], cancelled: [] }); const [rows, setRows] = useState(firstRow); const [allocationRows, setAllocationRows] = useState(firstRow); const [source, setSource] = useState(''); const [reference, setReference] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [pendingAction, setPendingAction] = useState(null); const receiptId = useRef(uuid()); const allocationId = useRef(uuid()); const mutationId = useRef(uuid());
  useEffect(() => { if (!branchId) return undefined; let live = true; setAllocations({ pending: [], confirmed: [], cancelled: [] }); const stopCatalog = subscribeActiveGiftItems((items) => live && setCatalog(items), () => live && setError(giftCallableMessage())); const stopPending = subscribeGiftAllocations(identity, { branchId, status: 'pending' }, (items) => live && setAllocations((current) => ({ ...current, pending: items })), () => live && setError(giftCallableMessage())); const stopConfirmed = subscribeGiftAllocations(identity, { branchId, status: 'confirmed' }, (items) => live && setAllocations((current) => ({ ...current, confirmed: items })), () => live && setError(giftCallableMessage())); const stopCancelled = subscribeGiftAllocations(identity, { branchId, status: 'cancelled' }, (items) => live && setAllocations((current) => ({ ...current, cancelled: items })), () => live && setError(giftCallableMessage())); return () => { live = false; stopCatalog?.(); stopPending?.(); stopConfirmed?.(); stopCancelled?.(); }; }, [branchId, identity]);
  const submitReceipt = async (event) => { event.preventDefault(); const result = validateGiftItemRows(rows, catalog); if (!source.trim()) { setError('Receipt source is required'); return; } if (result.error) { setError(result.error); return; } setBusy(true); setError(''); try { await receiveGiftStock({ receiptId: receiptId.current, branchId, source: source.trim(), reference: reference.trim(), items: result.items }); receiptId.current = uuid(); setRows(firstRow()); setSource(''); setReference(''); } catch (failure) { setError(giftCallableMessage(failure)); } finally { setBusy(false); } };
  const submitAllocation = async () => { const result = validateGiftItemRows(allocationRows, catalog); if (!source.trim()) { setError('Allocation source is required'); return; } if (result.error) { setError(result.error); return; } setBusy(true); setError(''); try { await createGiftAllocation({ allocationId: allocationId.current, targetBranchId: branchId, source: source.trim(), reference: reference.trim(), items: result.items }); allocationId.current = uuid(); setAllocationRows(firstRow()); } catch (failure) { setError(giftCallableMessage(failure)); } finally { setBusy(false); } };
  const confirmAction = async () => { if (!pendingAction) return; setBusy(true); setError(''); try { if (pendingAction.type === 'confirm') await confirmGiftAllocation({ allocationId: pendingAction.id, mutationId: mutationId.current }); else await cancelGiftAllocation({ allocationId: pendingAction.id, mutationId: mutationId.current, reason: 'Cancelled by branch' }); mutationId.current = uuid(); setPendingAction(null); } catch (failure) { setError(giftCallableMessage(failure)); } finally { setBusy(false); } };
  const cancelling = pendingAction?.type === 'cancel';
  return <GlassCard as="section" padded><h2>ຮັບເຂົ້າ</h2><form className="form-stack" onSubmit={submitReceipt}><Input id="gift-receipt-source" label="Receipt source" value={source} disabled={busy} onChange={(event) => setSource(event.target.value)} /><Input id="gift-receipt-reference" label="Receipt reference" value={reference} disabled={busy} onChange={(event) => setReference(event.target.value)} /><GiftItemRows catalog={catalog} rows={rows} onChange={setRows} maxRows={25} disabled={busy} /><Button type="submit" busy={busy} disabled={!branchId}>Receive stock</Button></form>{admin ? <section><h3>Allocation</h3><GiftItemRows catalog={catalog} rows={allocationRows} onChange={setAllocationRows} maxRows={25} disabled={busy} /><Button disabled={busy || !branchId} onClick={submitAllocation}>Create allocation</Button></section> : null}<section><h3>Pending allocation</h3>{allocations.pending.map((allocation) => <div key={allocation.id}><strong>{allocation.source}</strong><Button disabled={busy} onClick={() => setPendingAction({ type: 'confirm', id: allocation.id })}>Confirm allocation</Button><Button variant="neutral" disabled={busy} onClick={() => setPendingAction({ type: 'cancel', id: allocation.id })}>Cancel allocation</Button></div>)}</section><section><h3>Confirmed allocation</h3>{allocations.confirmed.map((allocation) => <div key={allocation.id}><strong>{allocation.source}</strong><Button disabled>Confirmed</Button></div>)}</section><section><h3>Cancelled allocation</h3>{allocations.cancelled.map((allocation) => <div key={allocation.id}><strong>{allocation.source}</strong><Button disabled>Cancelled</Button></div>)}</section>{error ? <div role="alert" className="error-banner">{error}</div> : null}<ModalSheet open={Boolean(pendingAction)} onClose={() => !busy && setPendingAction(null)} title={cancelling ? 'Cancel allocation' : 'Confirm allocation'} footer={<><Button variant="neutral" disabled={busy} onClick={() => setPendingAction(null)}>Back</Button><Button busy={busy} onClick={confirmAction}>{cancelling ? 'Cancel allocation' : 'Confirm'}</Button></>}><p>{cancelling ? 'Cancelling does not update stock.' : 'Confirming updates stock only after this action.'}</p></ModalSheet></GlassCard>;
}
