import { useEffect, useState } from 'react';
import { createGiftCampaign, subscribeGiftCampaigns, updateGiftCampaign } from '../services/giftService';
import { BRANCHES } from '../branches/branches';
import { giftCallableMessage } from './giftErrors';
import Button from '../components/ui/Button';
import GlassCard from '../components/ui/GlassCard';
import Input from '../components/ui/Input';
import Textarea from '../components/ui/Textarea';

const actor = (identity) => ({ role: identity?.claims?.role ?? identity?.role, branchId: identity?.claims?.branchId ?? identity?.branchId });
const branchFor = (identity, effective) => actor(identity).role === 'admin' ? effective : actor(identity).branchId;
const blank = (branchId) => ({ name: '', branchId, startDate: '', endDate: '', note: '', active: true });
export default function GiftCampaignAdmin({ identity, effectiveBranchId }) {
  const admin = actor(identity).role === 'admin'; const branchId = branchFor(identity, effectiveBranchId); const [campaigns, setCampaigns] = useState([]); const [draft, setDraft] = useState(() => blank(branchId)); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { setDraft((current) => current.id ? current : { ...current, branchId }); }, [branchId]);
  useEffect(() => { if (!branchId) return undefined; let live = true; const merge = (next) => { if (!live) return; setCampaigns((current) => [...new Map([...current.filter((item) => item.active !== next[0]?.active), ...next].map((item) => [item.id, item])).values()]); }; const stopActive = subscribeGiftCampaigns(identity, { branchId, active: true }, merge, () => live && setError(giftCallableMessage())); const stopInactive = subscribeGiftCampaigns(identity, { branchId, active: false }, merge, () => live && setError(giftCallableMessage())); return () => { live = false; stopActive?.(); stopInactive?.(); }; }, [branchId, identity]);
  const set = (field, value) => setDraft((current) => ({ ...current, [field]: value }));
  const submit = async (event) => { event.preventDefault(); const targetBranch = admin ? draft.branchId : branchId; if (!targetBranch || !draft.name.trim() || !/^\d{4}-\d{2}-\d{2}$/.test(draft.startDate) || !/^\d{4}-\d{2}-\d{2}$/.test(draft.endDate) || draft.startDate > draft.endDate) { setError('Campaign date range is invalid'); return; } setBusy(true); setError(''); try { const values = { ...draft, name: draft.name.trim(), branchId: targetBranch }; if (draft.id) await updateGiftCampaign(draft.id, values); else await createGiftCampaign(values); setDraft(blank(targetBranch)); } catch (failure) { setError(giftCallableMessage(failure)); } finally { setBusy(false); } };
  return <GlassCard as="section" padded><h2>Campaign</h2><form className="form-stack" onSubmit={submit}><Input id="campaign-name" label="Campaign name" value={draft.name} disabled={busy} onChange={(event) => set('name', event.target.value)} /><label>Campaign branch<select aria-label="Campaign branch" value={draft.branchId ?? ''} disabled={busy || !admin} onChange={(event) => set('branchId', event.target.value)}>{!draft.branchId ? <option value="">ເລືອກສາຂາ</option> : null}{BRANCHES.map((branch) => <option key={branch.id} value={branch.id}>{branch.label}</option>)}</select></label><Input id="campaign-start" label="Start date" type="date" value={draft.startDate} disabled={busy} onChange={(event) => set('startDate', event.target.value)} /><Input id="campaign-end" label="End date" type="date" value={draft.endDate} disabled={busy} onChange={(event) => set('endDate', event.target.value)} /><Textarea id="campaign-note" label="Campaign note" value={draft.note} disabled={busy} onChange={(event) => set('note', event.target.value)} /><label><input aria-label="Campaign active" type="checkbox" checked={draft.active} disabled={busy} onChange={(event) => set('active', event.target.checked)} /> Active</label>{error ? <div role="alert" className="error-banner">{error}</div> : null}<Button type="submit" busy={busy} disabled={!branchId}>Save campaign</Button></form><section><h3>Campaign history</h3>{campaigns.map((campaign) => <div key={campaign.id}><strong>{campaign.name}</strong> <small>{campaign.active ? 'Active' : 'Inactive'}</small><Button variant="neutral" disabled={busy} onClick={() => setDraft({ ...campaign })}>Edit</Button></div>)}</section></GlassCard>;
}
