import { useEffect, useMemo, useState } from 'react';
import { createGiftCampaign, subscribeGiftCampaigns, updateGiftCampaign } from '../services/giftService';
import { BRANCHES } from '../branches/branches';
import { giftCallableMessage } from './giftErrors';
import Button from '../components/ui/Button';
import CustomSelect from '../components/ui/CustomSelect';
import GlassCard from '../components/ui/GlassCard';
import Input from '../components/ui/Input';
import Textarea from '../components/ui/Textarea';
import { giftLabel } from './giftLabels';

const actor = (identity) => ({ role: identity?.claims?.role ?? identity?.role, branchId: identity?.claims?.branchId ?? identity?.branchId });
const branchFor = (identity, effective) => actor(identity).role === 'admin' ? effective : actor(identity).branchId;
const blank = (branchId) => ({ name: '', branchId, startDate: '', endDate: '', note: '', active: true });
export default function GiftCampaignAdmin({ identity, effectiveBranchId }) {
  const admin = actor(identity).role === 'admin'; const branchId = branchFor(identity, effectiveBranchId); const [activeCampaigns, setActiveCampaigns] = useState([]); const [inactiveCampaigns, setInactiveCampaigns] = useState([]); const [draft, setDraft] = useState(() => blank(branchId)); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { setDraft((current) => current.id ? current : { ...current, branchId }); }, [branchId]);
  useEffect(() => { if (!branchId) return undefined; let live = true; setActiveCampaigns([]); setInactiveCampaigns([]); const stopActive = subscribeGiftCampaigns(identity, { branchId, active: true }, (next) => { if (live) setActiveCampaigns(next.filter((item) => item.active)); }, () => live && setError(giftCallableMessage())); const stopInactive = subscribeGiftCampaigns(identity, { branchId, active: false }, (next) => { if (live) setInactiveCampaigns(next.filter((item) => !item.active)); }, () => live && setError(giftCallableMessage())); return () => { live = false; stopActive?.(); stopInactive?.(); }; }, [branchId, identity]);
  const campaigns = useMemo(() => [...activeCampaigns, ...inactiveCampaigns], [activeCampaigns, inactiveCampaigns]);
  const set = (field, value) => setDraft((current) => ({ ...current, [field]: value }));
  const submit = async (event) => { event.preventDefault(); const targetBranch = admin ? draft.branchId : branchId; if (!targetBranch || !draft.name.trim() || !/^\d{4}-\d{2}-\d{2}$/.test(draft.startDate) || !/^\d{4}-\d{2}-\d{2}$/.test(draft.endDate) || draft.startDate > draft.endDate) { setError('ຊ່ວງວັນທີແຄມເປນບໍ່ຖືກຕ້ອງ'); return; } setBusy(true); setError(''); try { const values = { ...draft, name: draft.name.trim(), branchId: targetBranch }; if (draft.id) await updateGiftCampaign(draft.id, values); else await createGiftCampaign(values); setDraft(blank(targetBranch)); } catch (failure) { setError(giftCallableMessage(failure)); } finally { setBusy(false); } };
  return <GlassCard as="section" padded><h2>{giftLabel('campaign')}</h2><form className="form-stack" onSubmit={submit}><Input id="campaign-name" label={giftLabel('campaignName')} value={draft.name} disabled={busy} onChange={(event) => set('name', event.target.value)} /><CustomSelect id="campaign-branch" label={giftLabel('campaignBranch')} value={draft.branchId ?? ''} disabled={busy || !admin} onChange={(value) => set('branchId', value)} placeholder="ເລືອກສາຂາ" options={BRANCHES.map((branch) => ({ value: branch.id, label: branch.label }))} /><Input id="campaign-start" label={giftLabel('startDate')} type="date" value={draft.startDate} disabled={busy} onChange={(event) => set('startDate', event.target.value)} /><Input id="campaign-end" label={giftLabel('endDate')} type="date" value={draft.endDate} disabled={busy} onChange={(event) => set('endDate', event.target.value)} /><Textarea id="campaign-note" label={giftLabel('campaignNote')} value={draft.note} disabled={busy} onChange={(event) => set('note', event.target.value)} /><label className="gift-checkbox-row"><input className="gift-checkbox" aria-label={`${giftLabel('campaign')} ${giftLabel('active')}`} type="checkbox" checked={draft.active} disabled={busy} onChange={(event) => set('active', event.target.checked)} /> {giftLabel(draft.active ? 'active' : 'inactive')}</label>{error ? <div role="alert" className="error-banner">{error}</div> : null}<Button type="submit" busy={busy} disabled={!branchId}>{giftLabel('saveCampaign')}</Button></form><section><h3>{giftLabel('campaignHistory')}</h3>{campaigns.map((campaign) => <div key={campaign.id}><strong>{campaign.name}</strong> <small>{giftLabel(campaign.active ? 'active' : 'inactive')}</small><Button variant="neutral" disabled={busy} onClick={() => setDraft({ ...campaign })}>{giftLabel('edit')}</Button></div>)}</section></GlassCard>;
}
