import { useRef, useState } from 'react'; import { ACTIVITY_STATUSES, ACTIVITY_TYPES, activityStatusLabel, activityTypeLabel } from '../shared/constants'; import { fromLaosDateTimeInput, toInputDateTime } from '../shared/dateTime'; import { BRANCHES } from '../branches/branches';
import CustomSelect from '../components/ui/CustomSelect'; import SearchableSelect from '../components/ui/SearchableSelect'; import DateField from '../components/ui/DateField';

export default function ActivityForm({ initial = {}, type, customers, users, currentUid, onSubmit, busy, admin = false }) {
  const initialPurpose = initial.purpose ?? initial.visitPurpose ?? '';
  const initialValues = { type, title: '', status: 'planned', branchId: '010', location: '', purpose: initialPurpose, note: '', customerId: '', assignedStaffIds: [currentUid].filter(Boolean), preVisitNotes: '', visitNotes: '', result: '', followUpRequired: false, nextAction: '', ...initial };
  const [values, setValues] = useState({ ...initialValues, purpose: initialPurpose, productServicesText: Array.isArray(initial.productServices) ? initial.productServices.join(', ') : initial.productServicesText || '', startAt: toInputDateTime(initial.startAt) || initial.startAt || '', endAt: toInputDateTime(initial.endAt) || initial.endAt || '', followUpDate: toInputDateTime(initial.followUpDate) || initial.followUpDate || '' });
  const [customerError, setCustomerError] = useState(''); const customerRef = useRef(null);
  const field = (name) => ({ value: values[name] ?? '', onChange: (event) => setValues({ ...values, [name]: event.target.value }) });
  const toggleUser = (uid) => setValues({ ...values, assignedStaffIds: values.assignedStaffIds.includes(uid) ? values.assignedStaffIds.filter((item) => item !== uid) : [...values.assignedStaffIds, uid] });
  const submit = (event) => { event.preventDefault(); if (type === ACTIVITY_TYPES.CUSTOMER_VISIT && !values.customerId) { setCustomerError('ນັດພົບລູກຄ້າຕ້ອງເລືອກລູກຄ້າ'); customerRef.current?.focus(); return; } if (!event.currentTarget.checkValidity()) { event.currentTarget.reportValidity(); return; } const payload = { ...values }; delete payload.visitPurpose; onSubmit({ ...payload, type, startAt: fromLaosDateTimeInput(values.startAt).toISOString(), endAt: fromLaosDateTimeInput(values.endAt).toISOString(), customerId: values.customerId || null, productServices: values.productServicesText.split(',').map((item) => item.trim()).filter(Boolean), followUpDate: values.followUpRequired && values.followUpDate ? fromLaosDateTimeInput(values.followUpDate).toISOString() : null }); };
  const availableUsers = admin ? users.filter((user) => user.branchId === values.branchId) : users;
  const availableCustomers = admin ? customers.filter((customer) => customer.branchId === values.branchId) : customers;
  const branchOptions = BRANCHES.map((branch) => ({ value: branch.id, label: branch.label })); const statusOptions = ACTIVITY_STATUSES.map((status) => ({ value: status, label: activityStatusLabel(status) })); const customerOptions = [{ value: '', label: '— ບໍ່ເລືອກ —' }, ...availableCustomers.map((customer) => ({ value: customer.id, label: `${customer.name} · ${customer.phone}`, searchText: `${customer.name} ${customer.phone}` }))];
  return <form className="form-stack panel" noValidate onSubmit={submit}><div className="eyebrow">{activityTypeLabel(type)}</div>{admin && !initial.id && <CustomSelect id="activity-branch" label="ສາຂາ" value={values.branchId} options={branchOptions} onChange={(branchId) => setValues({ ...values, branchId, customerId: '', assignedStaffIds: [] })}/>}<label>ຫົວຂໍ້<input required {...field('title')}/></label><div className="form-grid"><DateField id="activity-start" type="datetime-local" label="ເລີ່ມ" required value={values.startAt} onChange={(event) => setValues({ ...values, startAt: event.target.value })}/><DateField id="activity-end" type="datetime-local" label="ສິ້ນສຸດ" required value={values.endAt} onChange={(event) => setValues({ ...values, endAt: event.target.value })}/></div>
    <label>ສະຖານທີ່<input {...field('location')}/></label><SearchableSelect ref={customerRef} id="activity-customer" label={`ລູກຄ້າ ${type === ACTIVITY_TYPES.CUSTOMER_VISIT ? '(ຈຳເປັນ)' : '(ບໍ່ບັງຄັບ)'}`} value={values.customerId} options={customerOptions} onChange={(customerId) => { setValues({ ...values, customerId }); setCustomerError(''); }} searchPlaceholder="ຄົ້ນຫາຊື່ ຫຼື ເບີໂທ" required={type === ACTIVITY_TYPES.CUSTOMER_VISIT} error={customerError}/>
    <fieldset><legend>ພະນັກງານຮັບຜິດຊອບ</legend><div className="assignee-grid">{availableUsers.map((user) => <label className="check-card" key={user.uid}><input type="checkbox" checked={values.assignedStaffIds.includes(user.uid)} onChange={() => toggleUser(user.uid)}/><span>{user.name || user.email}</span></label>)}</div></fieldset>
    <label>{type === ACTIVITY_TYPES.CUSTOMER_VISIT ? 'ຈຸດປະສົງການນັດພົບ' : 'ຈຸດປະສົງ'}<input {...field('purpose')}/></label>{type === ACTIVITY_TYPES.CUSTOMER_VISIT && <><label>ສິນຄ້າ / ບໍລິການ (ຂັ້ນດ້ວຍໝາຍຈຸດ)<input {...field('productServicesText')}/></label><label>ບັນທຶກກ່ອນນັດພົບ<textarea rows="2" {...field('preVisitNotes')}/></label><label>ບັນທຶກການນັດພົບ<textarea rows="3" {...field('visitNotes')}/></label><label>ຜົນການນັດພົບ<textarea rows="2" {...field('result')}/></label><label className="check-card"><input type="checkbox" checked={values.followUpRequired} onChange={(event) => setValues({ ...values, followUpRequired: event.target.checked })}/><span>ຕ້ອງຕິດຕາມຕໍ່</span></label>{values.followUpRequired && <div className="form-grid"><DateField id="activity-follow-up-date" type="datetime-local" label="ວັນເວລາຕິດຕາມ" required value={values.followUpDate} onChange={(event) => setValues({ ...values, followUpDate: event.target.value })}/><label>ການດຳເນີນການຕໍ່ໄປ<input required {...field('nextAction')}/></label></div>}</>}
    <label>ໝາຍເຫດ<textarea rows="3" {...field('note')}/></label><CustomSelect id="activity-status" label="ສະຖານະ" value={values.status} options={statusOptions} onChange={(status) => setValues({ ...values, status })}/><button className="btn-primary" disabled={busy}>{busy ? 'ກຳລັງບັນທຶກ...' : 'ບັນທຶກກິດຈະກຳ'}</button></form>;
}
