import { useState } from 'react'; import { ACTIVITY_STATUSES, ACTIVITY_TYPES } from '../shared/constants'; import { fromLaosDateTimeInput, toInputDateTime } from '../shared/dateTime'; import { BRANCHES } from '../branches/branches';

const labels = { appointment: 'ນັດໝາຍ', event: 'Event', customer_visit: 'Customer Visit' };
export default function ActivityForm({ initial = {}, type, customers, users, currentUid, onSubmit, busy, admin = false }) {
  const [values, setValues] = useState({ type, title: '', status: 'planned', branchId: '010', location: '', purpose: '', note: '', customerId: '', assignedStaffIds: [currentUid].filter(Boolean), visitPurpose: '', preVisitNotes: '', visitNotes: '', result: '', followUpRequired: false, nextAction: '', ...initial, productServicesText: Array.isArray(initial.productServices) ? initial.productServices.join(', ') : initial.productServicesText || '', startAt: toInputDateTime(initial.startAt) || initial.startAt || '', endAt: toInputDateTime(initial.endAt) || initial.endAt || '', followUpDate: toInputDateTime(initial.followUpDate) || initial.followUpDate || '' });
  const field = (name) => ({ value: values[name] ?? '', onChange: (event) => setValues({ ...values, [name]: event.target.value }) });
  const toggleUser = (uid) => setValues({ ...values, assignedStaffIds: values.assignedStaffIds.includes(uid) ? values.assignedStaffIds.filter((item) => item !== uid) : [...values.assignedStaffIds, uid] });
  const submit = (event) => { event.preventDefault(); onSubmit({ ...values, type, startAt: fromLaosDateTimeInput(values.startAt).toISOString(), endAt: fromLaosDateTimeInput(values.endAt).toISOString(), customerId: values.customerId || null, productServices: values.productServicesText.split(',').map((item) => item.trim()).filter(Boolean), followUpDate: values.followUpRequired && values.followUpDate ? fromLaosDateTimeInput(values.followUpDate).toISOString() : null }); };
  const availableUsers = admin ? users.filter((user) => user.branchId === values.branchId) : users;
  const availableCustomers = admin ? customers.filter((customer) => customer.branchId === values.branchId) : customers;
  return <form className="form-stack panel" onSubmit={submit}><div className="eyebrow">{labels[type]}</div>{admin && !initial.id && <label>ສາຂາ<select value={values.branchId} onChange={(event) => setValues({ ...values, branchId: event.target.value, customerId: '', assignedStaffIds: [] })}>{BRANCHES.map((branch) => <option value={branch.id} key={branch.id}>{branch.label}</option>)}</select></label>}<label>ຫົວຂໍ້<input required {...field('title')}/></label><div className="form-grid"><label>ເລີ່ມ<input type="datetime-local" required {...field('startAt')}/></label><label>ສິ້ນສຸດ<input type="datetime-local" required {...field('endAt')}/></label></div>
    <label>ສະຖານທີ່<input {...field('location')}/></label><label>ລູກຄ້າ {type === ACTIVITY_TYPES.CUSTOMER_VISIT ? '(ຈຳເປັນ)' : '(ບໍ່ບັງຄັບ)'}<select required={type === ACTIVITY_TYPES.CUSTOMER_VISIT} {...field('customerId')}><option value="">— ບໍ່ເລືອກ —</option>{availableCustomers.map((customer) => <option value={customer.id} key={customer.id}>{customer.name} · {customer.phone}</option>)}</select></label>
    <fieldset><legend>ພະນັກງານຮັບຜິດຊອບ</legend><div className="assignee-grid">{availableUsers.map((user) => <label className="check-card" key={user.uid}><input type="checkbox" checked={values.assignedStaffIds.includes(user.uid)} onChange={() => toggleUser(user.uid)}/><span>{user.name || user.email}</span></label>)}</div></fieldset>
    <label>ຈຸດປະສົງ<input {...field('purpose')}/></label>{type === ACTIVITY_TYPES.CUSTOMER_VISIT && <><label>Visit Purpose<input {...field('visitPurpose')}/></label><label>Product / Service (ຂັ້ນດ້ວຍ comma)<input {...field('productServicesText')}/></label><label>Pre-visit Notes<textarea rows="2" {...field('preVisitNotes')}/></label><label>Visit Notes<textarea rows="3" {...field('visitNotes')}/></label><label>Result<textarea rows="2" {...field('result')}/></label><label className="check-card"><input type="checkbox" checked={values.followUpRequired} onChange={(event) => setValues({ ...values, followUpRequired: event.target.checked })}/><span>ຕ້ອງ Follow-up</span></label>{values.followUpRequired && <div className="form-grid"><label>Follow-up Date<input type="datetime-local" required {...field('followUpDate')}/></label><label>Next Action<input required {...field('nextAction')}/></label></div>}</>}
    <label>ໝາຍເຫດ<textarea rows="3" {...field('note')}/></label><label>ສະຖານະ<select {...field('status')}>{ACTIVITY_STATUSES.map((status) => <option key={status}>{status}</option>)}</select></label><button className="btn-primary" disabled={busy}>{busy ? 'ກຳລັງບັນທຶກ...' : 'ບັນທຶກກິດຈະກຳ'}</button></form>;
}
