import { useEffect, useMemo, useState } from 'react';
import Navbar from '../components/Navbar'; import ActivityCard from './ActivityCard'; import { useAuth } from '../auth/useAuth'; import { subscribeActivities } from '../services/activitiesService'; import { ACTIVITY_STATUSES, ACTIVITY_TYPES } from '../shared/constants';
import { subscribeAssignableUsers } from '../services/usersService';
import { laosDayKey } from '../shared/dateTime';

export default function ActivitiesPage() {
  const identity = useAuth(); const [activities, setActivities] = useState([]); const [users, setUsers] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [filters, setFilters] = useState({ type: 'all', scope: 'branch', staff: 'all', status: 'all', date: '' });
  useEffect(() => subscribeActivities(identity, (items) => { setActivities(items); setLoading(false); }, (reason) => { console.error(reason); setError('ບໍ່ສາມາດໂຫຼດກິດຈະກຳ'); setLoading(false); }), [identity]);
  useEffect(() => subscribeAssignableUsers(identity, setUsers, (reason) => console.error(reason)), [identity]);
  const shown = useMemo(() => activities.filter((item) => (filters.type === 'all' || item.type === filters.type) && (filters.status === 'all' || item.status === filters.status) && (filters.scope === 'branch' || item.assignedStaffIds.includes(identity.user.uid)) && (filters.staff === 'all' || item.assignedStaffIds.includes(filters.staff)) && (!filters.date || laosDayKey(item.startAt) === filters.date)), [activities, filters, identity.user.uid]);
  return <><Navbar title="ກິດຈະກຳ"/><main className="page-content"><section className="filter-panel"><div className="chip-row">{[['all','ທັງໝົດ'], ...Object.values(ACTIVITY_TYPES).map((type) => [type, type === 'appointment' ? 'ນັດໝາຍ' : type === 'event' ? 'Event' : 'Customer Visit'])].map(([value,label]) => <button key={value} className={filters.type === value ? 'chip active' : 'chip'} onClick={() => setFilters({ ...filters, type: value })}>{label}</button>)}</div>
    <div className="form-grid"><select aria-label="Activity scope" value={filters.scope} onChange={(event) => setFilters({ ...filters, scope: event.target.value })}><option value="branch">Branch Activities</option><option value="mine">My Activities</option></select><select aria-label="Activity status" value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value })}><option value="all">ທຸກສະຖານະ</option>{ACTIVITY_STATUSES.map((status) => <option key={status}>{status}</option>)}</select><select aria-label="Assigned staff" value={filters.staff} onChange={(event) => setFilters({ ...filters, staff: event.target.value })}><option value="all">ພະນັກງານທັງໝົດ</option>{users.map((user) => <option key={user.uid} value={user.uid}>{user.name || user.email}</option>)}</select><input aria-label="Activity date" type="date" value={filters.date} onChange={(event) => setFilters({ ...filters, date: event.target.value })}/></div></section>
    {error && <div className="error-banner">{error}</div>}{loading ? <div className="page-state">ກຳລັງໂຫຼດ...</div> : <section className="activity-list">{shown.map((item) => <ActivityCard key={item.id} activity={item}/>) }{!shown.length && <div className="page-state">ບໍ່ພົບກິດຈະກຳ</div>}</section>}</main></>;
}
