import { useEffect, useState } from 'react'; import { Link, useNavigate, useParams } from 'react-router-dom'; import Navbar from '../components/Navbar'; import { cancelActivity, completeFollowUp, getActivity, trashActivity } from '../services/activitiesService'; import { useAuth } from '../auth/useAuth'; import { canEditActivity, canTrashActivity } from '../shared/permissions'; import { formatDateTime } from '../shared/dateTime';

export default function ActivityDetailPage() {
  const { id } = useParams(); const navigate = useNavigate(); const identity = useAuth(); const [activity, setActivity] = useState(null); const [error, setError] = useState(''); const [nextAction, setNextAction] = useState(''); const [nextDate, setNextDate] = useState('');
  useEffect(() => { getActivity(id).then((item) => item ? setActivity(item) : setError('ບໍ່ພົບກິດຈະກຳ')).catch(() => setError('ໂຫຼດບໍ່ສຳເລັດ')); }, [id]);
  if (error) return <><Navbar title="ກິດຈະກຳ" showBack/><div className="page-state">{error}</div></>; if (!activity) return <div className="page-state">ກຳລັງໂຫຼດ...</div>;
  const actor = { uid: identity.user.uid, role: identity.claims.role, branchId: identity.claims.branchId, accountStatus: identity.claims.accountStatus };
  const cancel = async () => { await cancelActivity(id); setActivity({ ...activity, status: 'cancelled' }); };
  const trash = async () => { if (window.confirm('ຍ້າຍໄປ Trash?')) { await trashActivity(id); navigate('/activities'); } };
  const follow = async () => { await completeFollowUp(id); setActivity({ ...activity, followUpCompletedAt: new Date() }); };
  const reschedule = async () => { if (!nextAction || !nextDate) return; await completeFollowUp(id, { nextAction, followUpDate: new Date(nextDate).toISOString() }); setActivity({ ...activity, nextAction, followUpDate: new Date(nextDate), followUpCompletedAt: null }); setNextAction(''); setNextDate(''); };
  return <><Navbar title={activity.title} showBack/><main className="page-content narrow space-y-4"><section className="panel"><div className="flex justify-between gap-3"><div><span className="eyebrow">{activity.type}</span><h1 className="text-2xl font-extrabold mt-1">{activity.title}</h1></div><span className={`activity-status ${activity.status}`}>{activity.status}</span></div>
    <div className="detail-list mt-5"><p><span>ເລີ່ມ</span><strong>{formatDateTime(activity.startAt)}</strong></p><p><span>ສິ້ນສຸດ</span><strong>{formatDateTime(activity.endAt)}</strong></p><p><span>ສະຖານທີ່</span><strong>{activity.location || '—'}</strong></p><p><span>ຈຸດປະສົງ</span><strong>{activity.purpose || activity.visitPurpose || '—'}</strong></p><p><span>Assigned</span><strong>{activity.assignedStaffIds.length} ຄົນ</strong></p><p><span>ໝາຍເຫດ</span><strong>{activity.note || activity.visitNotes || '—'}</strong></p></div>
    {activity.customerId && <Link className="btn-secondary inline-block mt-4" to={`/customers/${activity.customerId}`}>ເບິ່ງລູກຄ້າ</Link>}{activity.followUpRequired && !activity.followUpCompletedAt && <div className="follow-panel mt-4"><strong>Next Action: {activity.nextAction}</strong><p>{formatDateTime(activity.followUpDate)}</p><button className="btn-primary mt-3" onClick={follow}>Mark Follow-up Complete</button><div className="form-grid mt-3"><input aria-label="New next action" placeholder="New Next Action" value={nextAction} onChange={(event) => setNextAction(event.target.value)}/><input aria-label="New follow-up date" type="datetime-local" value={nextDate} onChange={(event) => setNextDate(event.target.value)}/></div><button className="btn-secondary mt-2" disabled={!nextAction || !nextDate} onClick={reschedule}>ກຳນົດ Follow-up ໃໝ່</button></div>}
    <div className="flex flex-wrap gap-2 mt-5">{canEditActivity(actor, activity) && <><Link className="btn-primary" to={`/activities/${id}/edit`}>ແກ້ໄຂ</Link>{activity.status !== 'cancelled' && <button className="btn-ghost" onClick={cancel}>Cancel</button>}</>}{canTrashActivity(actor, activity) && <button className="btn-danger" onClick={trash}>Trash</button>}</div>
  </section></main></>;
}
