import { useEffect, useMemo, useState } from 'react';
import Navbar from '../components/Navbar'; import ActivityCard from './ActivityCard'; import { useAuth } from '../auth/useAuth'; import { subscribeActivities } from '../services/activitiesService'; import { ACTIVITY_STATUSES, ACTIVITY_TYPES, activityStatusLabel, activityTypeLabel } from '../shared/constants';
import { subscribeAssignableUsers } from '../services/usersService';
import { laosDayKey } from '../shared/dateTime';
import CustomSelect from '../components/ui/CustomSelect'; import SearchableSelect from '../components/ui/SearchableSelect'; import DateField from '../components/ui/DateField'; import GlassCard from '../components/ui/GlassCard';

export default function ActivitiesPage() {
  const identity = useAuth(); const [activities, setActivities] = useState([]); const [users, setUsers] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [filters, setFilters] = useState({ type: 'all', scope: 'branch', staff: 'all', status: 'all', date: '' });
  useEffect(() => subscribeActivities(identity, (items) => { setActivities(items); setLoading(false); }, (reason) => { console.error(reason); setError('ບໍ່ສາມາດໂຫຼດກິດຈະກຳ'); setLoading(false); }), [identity]);
  useEffect(() => subscribeAssignableUsers(identity, setUsers, (reason) => console.error(reason)), [identity]);
  const shown = useMemo(() => activities.filter((item) => (filters.type === 'all' || item.type === filters.type) && (filters.status === 'all' || item.status === filters.status) && (filters.scope === 'branch' || item.assignedStaffIds.includes(identity.user.uid)) && (filters.staff === 'all' || item.assignedStaffIds.includes(filters.staff)) && (!filters.date || laosDayKey(item.startAt) === filters.date)), [activities, filters, identity.user.uid]);
  const scopeOptions = [{ value: 'branch', label: 'ກິດຈະກຳຂອງສາຂາ' }, { value: 'mine', label: 'ກິດຈະກຳຂອງຂ້ອຍ' }]; const statusOptions = [{ value: 'all', label: 'ທຸກສະຖານະ' }, ...ACTIVITY_STATUSES.map((status) => ({ value: status, label: activityStatusLabel(status) }))]; const staffOptions = [{ value: 'all', label: 'ພະນັກງານທັງໝົດ' }, ...users.map((user) => ({ value: user.uid, label: user.name || user.email, searchText: `${user.name || ''} ${user.email || ''}` }))];
  return <><Navbar title="ກິດຈະກຳ"/><main className="page-content"><GlassCard as="section" className="filter-panel"><div className="chip-row">{[['all','ທັງໝົດ'], ...Object.values(ACTIVITY_TYPES).map((type) => [type, activityTypeLabel(type)])].map(([value,label]) => <button key={value} className={filters.type === value ? 'chip active' : 'chip'} onClick={() => setFilters({ ...filters, type: value })}>{label}</button>)}</div>
    <div className="form-grid"><CustomSelect id="activities-scope" label="ຂອບເຂດກິດຈະກຳ" value={filters.scope} options={scopeOptions} onChange={(scope) => setFilters({ ...filters, scope })}/><CustomSelect id="activities-status" label="ສະຖານະກິດຈະກຳ" value={filters.status} options={statusOptions} onChange={(status) => setFilters({ ...filters, status })}/><SearchableSelect id="activities-staff" label="ພະນັກງານຮັບຜິດຊອບ" value={filters.staff} options={staffOptions} onChange={(staff) => setFilters({ ...filters, staff })} searchPlaceholder="ຄົ້ນຫາພະນັກງານ"/><DateField id="activities-date" type="date" label="ວັນທີກິດຈະກຳ" value={filters.date} onChange={(event) => setFilters({ ...filters, date: event.target.value })}/></div></GlassCard>
    {error && <div className="error-banner">{error}</div>}{loading ? <div className="page-state">ກຳລັງໂຫຼດ...</div> : <section className="activity-list">{shown.map((item) => <ActivityCard key={item.id} activity={item}/>) }{!shown.length && <div className="page-state">ບໍ່ພົບກິດຈະກຳ</div>}</section>}</main></>;
}
