import { useEffect, useMemo, useState } from 'react'; import { Link } from 'react-router-dom'; import Navbar from '../components/Navbar'; import { useAuth } from '../auth/useAuth'; import { subscribeActivities } from '../services/activitiesService'; import { ACTIVITY_TYPES } from '../shared/constants'; import { toDate } from '../shared/dateTime';
import { subscribeAssignableUsers } from '../services/usersService';

export default function CalendarPage() {
  const identity = useAuth(); const [activities, setActivities] = useState([]); const [users, setUsers] = useState([]); const [filters, setFilters] = useState({ type: 'all', scope: 'branch', staff: 'all', status: 'all' });
  useEffect(() => subscribeActivities(identity, setActivities, (reason) => console.error(reason)), [identity]);
  useEffect(() => subscribeAssignableUsers(identity, setUsers, (reason) => console.error(reason)), [identity]);
  const groups = useMemo(() => {
    const result = new Map(); activities.filter((item) => (filters.type === 'all' || item.type === filters.type) && (filters.status === 'all' || item.status === filters.status) && (filters.scope === 'branch' || item.assignedStaffIds.includes(identity.user.uid)) && (filters.staff === 'all' || item.assignedStaffIds.includes(filters.staff))).sort((a,b) => toDate(a.startAt) - toDate(b.startAt)).forEach((item) => { const key = toDate(item.startAt)?.toISOString().slice(0,10) || 'unknown'; result.set(key, [...(result.get(key) || []), item]); }); return [...result.entries()];
  }, [activities, filters, identity.user.uid]);
  return <><Navbar title="ປະຕິທິນ"/><main className="page-content"><section className="filter-panel"><div className="form-grid"><select aria-label="Calendar type" value={filters.type} onChange={(event) => setFilters({ ...filters, type: event.target.value })}><option value="all">All Types</option>{Object.values(ACTIVITY_TYPES).map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Calendar scope" value={filters.scope} onChange={(event) => setFilters({ ...filters, scope: event.target.value })}><option value="branch">Branch Activities</option><option value="mine">My Activities</option></select><select aria-label="Calendar staff" value={filters.staff} onChange={(event) => setFilters({ ...filters, staff: event.target.value })}><option value="all">All Staff</option>{users.map((user) => <option value={user.uid} key={user.uid}>{user.name || user.email}</option>)}</select><select aria-label="Calendar status" value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value })}><option value="all">All Statuses</option><option value="planned">planned</option><option value="confirmed">confirmed</option><option value="in_progress">in_progress</option><option value="completed">completed</option><option value="cancelled">cancelled</option></select></div></section>
    <div className="calendar-groups">{groups.map(([date, items]) => <section key={date} className="calendar-day"><div className="calendar-date"><strong>{new Date(`${date}T00:00:00`).toLocaleDateString('lo-LA', { weekday: 'short', day: 'numeric', month: 'short' })}</strong><Link to={`/activities/new/appointment?date=${date}`}>＋</Link></div><div>{items.map((item) => <Link key={item.id} to={`/activities/${item.id}`} className={`calendar-item ${item.type}`}><span>{new Date(toDate(item.startAt)).toLocaleTimeString('lo-LA', { hour: '2-digit', minute: '2-digit' })}</span><strong>{item.title}</strong><small>{item.status}</small></Link>)}</div></section>)}{!groups.length && <div className="page-state">ບໍ່ມີກິດຈະກຳໃນປະຕິທິນ</div>}</div>
  </main></>;
}
