import { useEffect, useMemo, useState } from 'react'; import { Link } from 'react-router-dom'; import Navbar from '../components/Navbar'; import { useAuth } from '../auth/useAuth'; import { subscribeActivities } from '../services/activitiesService'; import { ACTIVITY_STATUSES, ACTIVITY_TYPES, activityStatusLabel, activityTypeLabel } from '../shared/constants'; import { formatLaosTime, laosDayKey, toDate } from '../shared/dateTime';
import { subscribeAssignableUsers } from '../services/usersService';
import CustomSelect from '../components/ui/CustomSelect'; import SearchableSelect from '../components/ui/SearchableSelect'; import GlassCard from '../components/ui/GlassCard'; import StatusBadge from '../components/ui/StatusBadge';

export default function CalendarPage() {
  const identity = useAuth(); const [activities, setActivities] = useState([]); const [users, setUsers] = useState([]); const [filters, setFilters] = useState({ type: 'all', scope: 'branch', staff: 'all', status: 'all' });
  useEffect(() => subscribeActivities(identity, setActivities, (reason) => console.error(reason)), [identity]);
  useEffect(() => subscribeAssignableUsers(identity, setUsers, (reason) => console.error(reason)), [identity]);
  const groups = useMemo(() => {
    const result = new Map(); activities.filter((item) => (filters.type === 'all' || item.type === filters.type) && (filters.status === 'all' || item.status === filters.status) && (filters.scope === 'branch' || item.assignedStaffIds.includes(identity.user.uid)) && (filters.staff === 'all' || item.assignedStaffIds.includes(filters.staff))).sort((a,b) => toDate(a.startAt) - toDate(b.startAt)).forEach((item) => { const key = laosDayKey(item.startAt) || 'unknown'; result.set(key, [...(result.get(key) || []), item]); }); return [...result.entries()];
  }, [activities, filters, identity.user.uid]);
  const typeOptions = [{ value: 'all', label: 'ທຸກປະເພດ' }, ...Object.values(ACTIVITY_TYPES).map((item) => ({ value: item, label: activityTypeLabel(item) }))]; const scopeOptions = [{ value: 'branch', label: 'ກິດຈະກຳຂອງສາຂາ' }, { value: 'mine', label: 'ກິດຈະກຳຂອງຂ້ອຍ' }]; const staffOptions = [{ value: 'all', label: 'ພະນັກງານທັງໝົດ' }, ...users.map((user) => ({ value: user.uid, label: user.name || user.email, searchText: `${user.name || ''} ${user.email || ''}` }))]; const statusOptions = [{ value: 'all', label: 'ທຸກສະຖານະ' }, ...ACTIVITY_STATUSES.map((status) => ({ value: status, label: activityStatusLabel(status) }))];
  return <><Navbar title="ປະຕິທິນ"/><main className="page-content"><GlassCard as="section" className="filter-panel calendar-filter-panel"><div className="form-grid"><CustomSelect id="calendar-type" label="ປະເພດໃນປະຕິທິນ" value={filters.type} options={typeOptions} onChange={(type) => setFilters({ ...filters, type })}/><CustomSelect id="calendar-scope" label="ຂອບເຂດປະຕິທິນ" value={filters.scope} options={scopeOptions} onChange={(scope) => setFilters({ ...filters, scope })}/><SearchableSelect id="calendar-staff" label="ພະນັກງານໃນປະຕິທິນ" value={filters.staff} options={staffOptions} onChange={(staff) => setFilters({ ...filters, staff })} searchPlaceholder="ຄົ້ນຫາພະນັກງານ"/><CustomSelect id="calendar-status" label="ສະຖານະໃນປະຕິທິນ" value={filters.status} options={statusOptions} onChange={(status) => setFilters({ ...filters, status })}/></div></GlassCard>
    <div className="calendar-groups">{groups.map(([date, items]) => <GlassCard as="section" key={date} className="calendar-day"><div className="calendar-date"><strong>{new Date(`${date}T00:00:00+07:00`).toLocaleDateString('lo-LA', { weekday: 'short', day: 'numeric', month: 'short', timeZone: 'Asia/Vientiane' })}</strong><Link className="calendar-add-action" to={`/activities/new/appointment?date=${date}`}>＋</Link></div><div>{items.map((item) => <Link key={item.id} to={`/activities/${item.id}`} className={`calendar-item ${item.type}`}><span>{formatLaosTime(item.startAt)}</span><strong>{item.title}</strong><small>{activityTypeLabel(item.type)} · <StatusBadge kind="activity" value={item.status} label={activityStatusLabel(item.status)}/></small></Link>)}</div></GlassCard>)}{!groups.length && <div className="page-state">ບໍ່ມີກິດຈະກຳໃນປະຕິທິນ</div>}</div>
  </main></>;
}
