import { useEffect, useMemo, useState } from 'react'; import { Link } from 'react-router-dom'; import Navbar from '../components/Navbar'; import { useAuth } from '../auth/useAuth'; import { subscribeActivities } from '../services/activitiesService'; import { ACTIVITY_STATUSES, ACTIVITY_TYPES, activityStatusLabel, activityTypeLabel } from '../shared/constants'; import { formatLaosTime, laosDayKey, toDate } from '../shared/dateTime';
import { subscribeAssignableUsers } from '../services/usersService';

export default function CalendarPage() {
  const identity = useAuth(); const [activities, setActivities] = useState([]); const [users, setUsers] = useState([]); const [filters, setFilters] = useState({ type: 'all', scope: 'branch', staff: 'all', status: 'all' });
  useEffect(() => subscribeActivities(identity, setActivities, (reason) => console.error(reason)), [identity]);
  useEffect(() => subscribeAssignableUsers(identity, setUsers, (reason) => console.error(reason)), [identity]);
  const groups = useMemo(() => {
    const result = new Map(); activities.filter((item) => (filters.type === 'all' || item.type === filters.type) && (filters.status === 'all' || item.status === filters.status) && (filters.scope === 'branch' || item.assignedStaffIds.includes(identity.user.uid)) && (filters.staff === 'all' || item.assignedStaffIds.includes(filters.staff))).sort((a,b) => toDate(a.startAt) - toDate(b.startAt)).forEach((item) => { const key = laosDayKey(item.startAt) || 'unknown'; result.set(key, [...(result.get(key) || []), item]); }); return [...result.entries()];
  }, [activities, filters, identity.user.uid]);
  return <><Navbar title="ປະຕິທິນ"/><main className="page-content"><section className="filter-panel"><div className="form-grid"><select aria-label="ປະເພດໃນປະຕິທິນ" value={filters.type} onChange={(event) => setFilters({ ...filters, type: event.target.value })}><option value="all">ທຸກປະເພດ</option>{Object.values(ACTIVITY_TYPES).map((item) => <option key={item} value={item}>{activityTypeLabel(item)}</option>)}</select><select aria-label="ຂອບເຂດປະຕິທິນ" value={filters.scope} onChange={(event) => setFilters({ ...filters, scope: event.target.value })}><option value="branch">ກິດຈະກຳຂອງສາຂາ</option><option value="mine">ກິດຈະກຳຂອງຂ້ອຍ</option></select><select aria-label="ພະນັກງານໃນປະຕິທິນ" value={filters.staff} onChange={(event) => setFilters({ ...filters, staff: event.target.value })}><option value="all">ພະນັກງານທັງໝົດ</option>{users.map((user) => <option value={user.uid} key={user.uid}>{user.name || user.email}</option>)}</select><select aria-label="ສະຖານະໃນປະຕິທິນ" value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value })}><option value="all">ທຸກສະຖານະ</option>{ACTIVITY_STATUSES.map((status) => <option key={status} value={status}>{activityStatusLabel(status)}</option>)}</select></div></section>
    <div className="calendar-groups">{groups.map(([date, items]) => <section key={date} className="calendar-day"><div className="calendar-date"><strong>{new Date(`${date}T00:00:00+07:00`).toLocaleDateString('lo-LA', { weekday: 'short', day: 'numeric', month: 'short', timeZone: 'Asia/Vientiane' })}</strong><Link to={`/activities/new/appointment?date=${date}`}>＋</Link></div><div>{items.map((item) => <Link key={item.id} to={`/activities/${item.id}`} className={`calendar-item ${item.type}`}><span>{formatLaosTime(item.startAt)}</span><strong>{item.title}</strong><small>{activityTypeLabel(item.type)} · {activityStatusLabel(item.status)}</small></Link>)}</div></section>)}{!groups.length && <div className="page-state">ບໍ່ມີກິດຈະກຳໃນປະຕິທິນ</div>}</div>
  </main></>;
}
