import { useEffect, useMemo, useState } from 'react'; import { Link } from 'react-router-dom'; import Navbar from '../components/Navbar'; import ActivityCard from '../activities/ActivityCard'; import { useAuth } from '../auth/useAuth'; import { subscribeCustomers } from '../services/customersService'; import { subscribeActivities } from '../services/activitiesService'; import { bucketFollowUp } from '../shared/followUp'; import { toDate } from '../shared/dateTime'; import { followUpBucketLabel } from '../shared/constants'; import GlassCard from '../components/ui/GlassCard';

export default function Home() {
  const identity = useAuth(); const [customers, setCustomers] = useState([]); const [activities, setActivities] = useState([]);
  useEffect(() => subscribeCustomers(identity, setCustomers, (reason) => console.error(reason)), [identity]);
  useEffect(() => subscribeActivities(identity, setActivities, (reason) => console.error(reason)), [identity]);
  const data = useMemo(() => { const todayKey = new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Vientiane' }); const today = activities.filter((item) => toDate(item.startAt)?.toLocaleDateString('en-CA', { timeZone: 'Asia/Vientiane' }) === todayKey); const typeCounts = { appointment: 0, event: 0, customer_visit: 0 }; today.forEach((item) => { typeCounts[item.type] += 1; }); const follow = { overdue: 0, today: 0, upcoming: 0 }; activities.forEach((item) => { const key = bucketFollowUp(item); if (key) follow[key] += 1; }); return { today, typeCounts, follow, recent: [...activities].sort((a,b) => toDate(b.updatedAt || b.createdAt) - toDate(a.updatedAt || a.createdAt)).slice(0,5) }; }, [activities]);
  return <><Navbar title="ໜ້າຫຼັກ"/><main className="page-content"><GlassCard as="section" variant="raised" className="welcome"><div><span className="eyebrow">WORK DASHBOARD</span><h1>ສະບາຍດີ, {identity.profile?.name || identity.user.email}</h1><p>ວຽກຂອງສາຂາມື້ນີ້</p></div><div className="customer-total"><strong>{customers.length}</strong><span>ລູກຄ້າ</span></div></GlassCard>
    <section className="summary-grid three"><GlassCard className="summary-card"><span>ນັດໝາຍມື້ນີ້</span><strong>{data.typeCounts.appointment}</strong></GlassCard><GlassCard className="summary-card"><span>ກິດຈະກຳມື້ນີ້</span><strong>{data.typeCounts.event}</strong></GlassCard><GlassCard className="summary-card"><span>ນັດພົບລູກຄ້າມື້ນີ້</span><strong>{data.typeCounts.customer_visit}</strong></GlassCard></section>
    <GlassCard as="section" className="dashboard-follow-up mt-5"><div className="section-heading"><h2>ຕິດຕາມຕໍ່</h2><Link to="/follow-up">ເບິ່ງທັງໝົດ</Link></div><div className="summary-grid three compact"><div className="mini-stat overdue"><span>{followUpBucketLabel('overdue')}</span><strong>{data.follow.overdue}</strong></div><div className="mini-stat"><span>{followUpBucketLabel('today')}</span><strong>{data.follow.today}</strong></div><div className="mini-stat upcoming"><span>{followUpBucketLabel('upcoming')}</span><strong>{data.follow.upcoming}</strong></div></div></GlassCard>
    <section className="mt-5"><div className="section-heading"><h2>ກິດຈະກຳຫຼ້າສຸດ</h2><Link to="/activities">ເບິ່ງທັງໝົດ</Link></div><div className="activity-list">{data.recent.map((item) => <ActivityCard key={item.id} activity={item}/>)}{!data.recent.length && <div className="page-state">ຍັງບໍ່ມີກິດຈະກຳ</div>}</div></section>
  </main></>;
}
