import { useEffect, useState } from 'react'; import Navbar from '../components/Navbar'; import { BRANCHES, branchName } from '../branches/branches'; import { approveUser, cleanupExpiredTrash, disableUser, permanentlyDeleteActivity, permanentlyDeleteCustomer, restoreActivity, restoreCustomer, subscribeTrash, subscribeUsers, updateUserAccess } from '../services/adminService';

function UserRow({ user }) {
  const [role, setRole] = useState(user.role || 'staff'); const [branchId, setBranchId] = useState(user.branchId || '010'); const [busy, setBusy] = useState(false);
  const save = async () => { setBusy(true); try { if (user.accountStatus === 'pending') await approveUser(user.uid, role, branchId); else await updateUserAccess(user.uid, role, branchId); } finally { setBusy(false); } };
  return <div className="admin-row"><div className="min-w-0"><strong className="block truncate">{user.name || user.email || user.uid}</strong><small>{user.accountStatus}</small></div><select value={role} onChange={(event) => setRole(event.target.value)}><option value="staff">Staff</option><option value="branch_manager">Branch Manager</option><option value="admin">Admin</option></select><select value={branchId} onChange={(event) => setBranchId(event.target.value)} disabled={role === 'admin'}>{BRANCHES.map((branch) => <option value={branch.id} key={branch.id}>{branch.label}</option>)}</select><button className="btn-primary" disabled={busy} onClick={save}>{user.accountStatus === 'pending' ? 'Approve' : 'Save'}</button>{user.accountStatus !== 'disabled' && <button className="btn-danger" onClick={() => disableUser(user.uid)}>Disable</button>}</div>;
}

export default function AdminPage() {
  const [tab, setTab] = useState('users'); const [userStatus, setUserStatus] = useState('pending'); const [users, setUsers] = useState([]); const [customers, setCustomers] = useState([]); const [activities, setActivities] = useState([]); const [error, setError] = useState('');
  useEffect(() => subscribeUsers(setUsers, (reason) => { console.error(reason); setError('Admin data load failed'); }), []);
  useEffect(() => subscribeTrash('customers', setCustomers, (reason) => console.error(reason)), []); useEffect(() => subscribeTrash('activities', setActivities, (reason) => console.error(reason)), []);
  const remove = async (kind, id) => { if (!window.confirm('Permanent delete? ການກະທຳນີ້ກູ້ຄືນບໍ່ໄດ້.')) return; if (kind === 'customer') await permanentlyDeleteCustomer(id); else await permanentlyDeleteActivity(id); };
  return <><Navbar title="Admin Center"/><main className="page-content"><div className="chip-row mb-5">{['users','branches','trash'].map((item) => <button key={item} className={tab === item ? 'chip active' : 'chip'} onClick={() => setTab(item)}>{item}</button>)}</div>{error && <div className="error-banner">{error}</div>}
    {tab === 'users' && <section className="panel"><div className="section-heading"><h2>Users</h2><span>{users.filter((user) => user.accountStatus === userStatus).length}</span></div><div className="chip-row mb-4">{['pending','approved','disabled'].map((status) => <button className={userStatus === status ? 'chip active' : 'chip'} onClick={() => setUserStatus(status)} key={status}>{status}</button>)}</div><div className="admin-list">{users.filter((user) => user.accountStatus === userStatus).map((user) => <UserRow key={user.uid} user={user}/>)}</div></section>}
    {tab === 'branches' && <section className="panel"><div className="section-heading"><h2>Branch Master</h2><span>{BRANCHES.length}</span></div><div className="branch-grid">{BRANCHES.map((branch) => <div key={branch.id}><strong>{branch.id}</strong><span>{branchName(branch.id)}</span><small>Active</small></div>)}</div></section>}
    {tab === 'trash' && <><div className="flex justify-end mb-4"><button className="btn-secondary" onClick={() => cleanupExpiredTrash()}>Run 30-day cleanup</button></div><div className="grid lg:grid-cols-2 gap-5"><section className="panel"><div className="section-heading"><h2>Customers Trash</h2><span>{customers.length}</span></div>{customers.map((item) => <div className="trash-row" key={item.id}><div><strong>{item.name}</strong><small>{item.branchId}</small></div><button className="btn-secondary" onClick={() => restoreCustomer(item.id)}>Restore</button><button className="btn-danger" onClick={() => remove('customer', item.id)}>Delete</button></div>)}</section><section className="panel"><div className="section-heading"><h2>Activities Trash</h2><span>{activities.length}</span></div>{activities.map((item) => <div className="trash-row" key={item.id}><div><strong>{item.title}</strong><small>{item.branchId}</small></div><button className="btn-secondary" onClick={() => restoreActivity(item.id)}>Restore</button><button className="btn-danger" onClick={() => remove('activity', item.id)}>Delete</button></div>)}</section></div></>}
  </main></>;
}
