import { useEffect, useState } from 'react'; import Navbar from '../components/Navbar'; import { BRANCHES, branchName } from '../branches/branches'; import { approveUser, cleanupExpiredTrash, disableUser, permanentlyDeleteActivity, permanentlyDeleteCustomer, reactivateUser, restoreActivity, restoreCustomer, subscribeTrash, subscribeUsers, updateUserAccess } from '../services/adminService';
import { ACCOUNT_STATUSES, ROLES, accountStatusLabel, roleLabel } from '../shared/constants';
import Button from '../components/ui/Button';
import CustomSelect from '../components/ui/CustomSelect';
import GlassCard from '../components/ui/GlassCard';

const roleOptions = Object.values(ROLES).map((value) => ({ value, label: roleLabel(value) }));
const branchOptions = BRANCHES.map((branch) => ({ value: branch.id, label: branch.label }));

function UserRow({ user }) {
  const [role, setRole] = useState(user.role || 'staff'); const [branchId, setBranchId] = useState(user.branchId || '010'); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const save = async () => { setBusy(true); setError(''); try { if (user.accountStatus === 'pending') await approveUser(user.uid, role, branchId); else if (user.accountStatus === 'disabled') await reactivateUser(user.uid, role, branchId); else await updateUserAccess(user.uid, role, branchId); } catch (reason) { console.error(reason); setError('ບໍ່ສາມາດປ່ຽນສະຖານະຜູ້ໃຊ້ໄດ້'); } finally { setBusy(false); } };
  const actionLabel = user.accountStatus === 'pending' ? 'ອະນຸມັດ' : user.accountStatus === 'disabled' ? 'ເປີດໃຊ້ງານຄືນ' : 'ບັນທຶກ';
  const userName = user.name || user.email || user.uid;
  return <div className="admin-row"><div className="min-w-0"><strong className="block truncate">{userName}</strong><small>{accountStatusLabel(user.accountStatus)}</small>{error && <small className="error-banner admin-row__error" role="alert">{error}</small>}</div><CustomSelect id={`user-${user.uid}-role`} ariaLabel={`ບົດບາດຂອງ ${userName}`} value={role} onChange={setRole} options={roleOptions} disabled={busy}/><CustomSelect id={`user-${user.uid}-branch`} ariaLabel={`ສາຂາຂອງ ${userName}`} value={branchId} onChange={setBranchId} options={branchOptions} disabled={busy || role === 'admin'}/><Button disabled={busy} onClick={save}>{actionLabel}</Button>{user.accountStatus !== 'disabled' && <Button variant="danger" disabled={busy} onClick={() => disableUser(user.uid)}>ປິດໃຊ້ງານ</Button>}</div>;
}

export default function AdminPage() {
  const [tab, setTab] = useState('users'); const [userStatus, setUserStatus] = useState('pending'); const [users, setUsers] = useState([]); const [customers, setCustomers] = useState([]); const [activities, setActivities] = useState([]); const [error, setError] = useState('');
  useEffect(() => subscribeUsers(setUsers, (reason) => { console.error(reason); setError('ໂຫຼດຂໍ້ມູນສູນບໍລິຫານບໍ່ສຳເລັດ'); }), []);
  useEffect(() => subscribeTrash('customers', setCustomers, (reason) => console.error(reason)), []); useEffect(() => subscribeTrash('activities', setActivities, (reason) => console.error(reason)), []);
  const remove = async (kind, id) => { if (!window.confirm('ຢືນຢັນການລຶບຖາວອນ? ການກະທຳນີ້ກູ້ຄືນບໍ່ໄດ້.')) return; if (kind === 'customer') await permanentlyDeleteCustomer(id); else await permanentlyDeleteActivity(id); };
  return <><Navbar title="ສູນບໍລິຫານ"/><main className="page-content"><div className="chip-row mb-5">{[['users','ຜູ້ໃຊ້'],['branches','ສາຂາ'],['trash','ຖັງຂີ້ເຫຍື້ອ']].map(([item, label]) => <Button variant="neutral" key={item} className={tab === item ? 'chip active' : 'chip'} onClick={() => setTab(item)}>{label}</Button>)}</div>{error && <div className="error-banner" role="alert">{error}</div>}
    {tab === 'users' && <GlassCard as="section" padded><div className="section-heading"><h2>ຜູ້ໃຊ້</h2><span>{users.filter((user) => user.accountStatus === userStatus).length}</span></div><div className="chip-row mb-4">{Object.values(ACCOUNT_STATUSES).map((status) => <Button variant="neutral" className={userStatus === status ? 'chip active' : 'chip'} onClick={() => setUserStatus(status)} key={status}>{accountStatusLabel(status)}</Button>)}</div><div className="admin-list">{users.filter((user) => user.accountStatus === userStatus).map((user) => <UserRow key={user.uid} user={user}/>)}</div></GlassCard>}
    {tab === 'branches' && <GlassCard as="section" padded><div className="section-heading"><h2>ລາຍຊື່ສາຂາ</h2><span>{BRANCHES.length}</span></div><div className="branch-grid">{BRANCHES.map((branch) => <div key={branch.id}><strong>{branch.id}</strong><span>{branchName(branch.id)}</span><small>ເປີດໃຊ້ງານ</small></div>)}</div></GlassCard>}
    {tab === 'trash' && <><div className="flex justify-end mb-4"><Button variant="secondary" onClick={() => cleanupExpiredTrash()}>ລຶບລາຍການທີ່ຄົບ 30 ວັນ</Button></div><div className="grid lg:grid-cols-2 gap-5"><GlassCard as="section" padded><div className="section-heading"><h2>ລູກຄ້າໃນຖັງຂີ້ເຫຍື້ອ</h2><span>{customers.length}</span></div>{customers.map((item) => <div className="trash-row" key={item.id}><div><strong>{item.name}</strong><small>{item.branchId}</small></div><Button variant="secondary" onClick={() => restoreCustomer(item.id)}>ກູ້ຄືນ</Button><Button variant="danger" onClick={() => remove('customer', item.id)}>ລຶບ</Button></div>)}</GlassCard><GlassCard as="section" padded><div className="section-heading"><h2>ກິດຈະກຳໃນຖັງຂີ້ເຫຍື້ອ</h2><span>{activities.length}</span></div>{activities.map((item) => <div className="trash-row" key={item.id}><div><strong>{item.title}</strong><small>{item.branchId}</small></div><Button variant="secondary" onClick={() => restoreActivity(item.id)}>ກູ້ຄືນ</Button><Button variant="danger" onClick={() => remove('activity', item.id)}>ລຶບ</Button></div>)}</GlassCard></div></>}
  </main></>;
}
