import { useEffect, useState } from 'react'; import Navbar from '../components/Navbar'; import { BRANCHES, branchName } from '../branches/branches'; import { approveUser, cleanupExpiredTrash, disableUser, permanentlyDeleteActivity, permanentlyDeleteCustomer, reactivateUser, restoreActivity, restoreCustomer, subscribeTrash, subscribeUsers, updateUserAccess } from '../services/adminService';
import { ACCOUNT_STATUSES, ROLES, accountStatusLabel, roleLabel } from '../shared/constants';

function UserRow({ user }) {
  const [role, setRole] = useState(user.role || 'staff'); const [branchId, setBranchId] = useState(user.branchId || '010'); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const save = async () => { setBusy(true); setError(''); try { if (user.accountStatus === 'pending') await approveUser(user.uid, role, branchId); else if (user.accountStatus === 'disabled') await reactivateUser(user.uid, role, branchId); else await updateUserAccess(user.uid, role, branchId); } catch (reason) { console.error(reason); setError('ບໍ່ສາມາດປ່ຽນສະຖານະຜູ້ໃຊ້ໄດ້'); } finally { setBusy(false); } };
  const actionLabel = user.accountStatus === 'pending' ? 'ອະນຸມັດ' : user.accountStatus === 'disabled' ? 'ເປີດໃຊ້ງານຄືນ' : 'ບັນທຶກ';
  return <div className="admin-row"><div className="min-w-0"><strong className="block truncate">{user.name || user.email || user.uid}</strong><small>{accountStatusLabel(user.accountStatus)}</small>{error && <small className="text-red-600 block">{error}</small>}</div><select value={role} onChange={(event) => setRole(event.target.value)} disabled={busy}>{Object.values(ROLES).map((value) => <option value={value} key={value}>{roleLabel(value)}</option>)}</select><select value={branchId} onChange={(event) => setBranchId(event.target.value)} disabled={busy || role === 'admin'}>{BRANCHES.map((branch) => <option value={branch.id} key={branch.id}>{branch.label}</option>)}</select><button className="btn-primary" disabled={busy} onClick={save}>{actionLabel}</button>{user.accountStatus !== 'disabled' && <button className="btn-danger" disabled={busy} onClick={() => disableUser(user.uid)}>ປິດໃຊ້ງານ</button>}</div>;
}

export default function AdminPage() {
  const [tab, setTab] = useState('users'); const [userStatus, setUserStatus] = useState('pending'); const [users, setUsers] = useState([]); const [customers, setCustomers] = useState([]); const [activities, setActivities] = useState([]); const [error, setError] = useState('');
  useEffect(() => subscribeUsers(setUsers, (reason) => { console.error(reason); setError('Admin data load failed'); }), []);
  useEffect(() => subscribeTrash('customers', setCustomers, (reason) => console.error(reason)), []); useEffect(() => subscribeTrash('activities', setActivities, (reason) => console.error(reason)), []);
  const remove = async (kind, id) => { if (!window.confirm('Permanent delete? ການກະທຳນີ້ກູ້ຄືນບໍ່ໄດ້.')) return; if (kind === 'customer') await permanentlyDeleteCustomer(id); else await permanentlyDeleteActivity(id); };
  return <><Navbar title="ສູນບໍລິຫານ"/><main className="page-content"><div className="chip-row mb-5">{[['users','ຜູ້ໃຊ້'],['branches','ສາຂາ'],['trash','ຖັງຂີ້ເຫຍື້ອ']].map(([item, label]) => <button key={item} className={tab === item ? 'chip active' : 'chip'} onClick={() => setTab(item)}>{label}</button>)}</div>{error && <div className="error-banner">{error}</div>}
    {tab === 'users' && <section className="panel"><div className="section-heading"><h2>ຜູ້ໃຊ້</h2><span>{users.filter((user) => user.accountStatus === userStatus).length}</span></div><div className="chip-row mb-4">{Object.values(ACCOUNT_STATUSES).map((status) => <button className={userStatus === status ? 'chip active' : 'chip'} onClick={() => setUserStatus(status)} key={status}>{accountStatusLabel(status)}</button>)}</div><div className="admin-list">{users.filter((user) => user.accountStatus === userStatus).map((user) => <UserRow key={user.uid} user={user}/>)}</div></section>}
    {tab === 'branches' && <section className="panel"><div className="section-heading"><h2>Branch Master</h2><span>{BRANCHES.length}</span></div><div className="branch-grid">{BRANCHES.map((branch) => <div key={branch.id}><strong>{branch.id}</strong><span>{branchName(branch.id)}</span><small>Active</small></div>)}</div></section>}
    {tab === 'trash' && <><div className="flex justify-end mb-4"><button className="btn-secondary" onClick={() => cleanupExpiredTrash()}>Run 30-day cleanup</button></div><div className="grid lg:grid-cols-2 gap-5"><section className="panel"><div className="section-heading"><h2>Customers Trash</h2><span>{customers.length}</span></div>{customers.map((item) => <div className="trash-row" key={item.id}><div><strong>{item.name}</strong><small>{item.branchId}</small></div><button className="btn-secondary" onClick={() => restoreCustomer(item.id)}>Restore</button><button className="btn-danger" onClick={() => remove('customer', item.id)}>Delete</button></div>)}</section><section className="panel"><div className="section-heading"><h2>Activities Trash</h2><span>{activities.length}</span></div>{activities.map((item) => <div className="trash-row" key={item.id}><div><strong>{item.title}</strong><small>{item.branchId}</small></div><button className="btn-secondary" onClick={() => restoreActivity(item.id)}>Restore</button><button className="btn-danger" onClick={() => remove('activity', item.id)}>Delete</button></div>)}</section></div></>}
  </main></>;
}
