import { lazy, Suspense } from 'react'; import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom'; import AuthProvider from './context/AuthContext'; import ProtectedRoute from './auth/ProtectedRoute'; import PendingPage from './auth/PendingPage'; import DisabledPage from './auth/DisabledPage'; import Login from './pages/Login'; import AppShell from './components/AppShell'; import BirthdayRemindersProvider from './birthdays/BirthdayRemindersProvider';

const Home=lazy(()=>import('./pages/Home')); const Profile=lazy(()=>import('./pages/Profile')); const CustomersPage=lazy(()=>import('./customers/CustomersPage')); const CustomerFormPage=lazy(()=>import('./customers/CustomerFormPage')); const CustomerDetailPage=lazy(()=>import('./customers/CustomerDetailPage')); const ActivitiesPage=lazy(()=>import('./activities/ActivitiesPage')); const ActivityFormPage=lazy(()=>import('./activities/ActivityFormPage')); const ActivityDetailPage=lazy(()=>import('./activities/ActivityDetailPage')); const FollowUpCenter=lazy(()=>import('./activities/FollowUpCenter')); const CalendarPage=lazy(()=>import('./activities/CalendarPage')); const AdminPage=lazy(()=>import('./admin/AdminPage'));

const protectedPage = (element, adminOnly = false) => <ProtectedRoute adminOnly={adminOnly}>{element}</ProtectedRoute>;
export default function App() {
  return <AuthProvider><BrowserRouter><Suspense fallback={<div className="page-state">ກຳລັງໂຫຼດ...</div>}><Routes><Route path="/login" element={<Login/>}/><Route path="/pending" element={<PendingPage/>}/><Route path="/disabled" element={<DisabledPage/>}/><Route element={protectedPage(<BirthdayRemindersProvider><AppShell/></BirthdayRemindersProvider>)}>
    <Route index element={<Home/>}/><Route path="customers" element={<CustomersPage/>}/><Route path="customers/new" element={<CustomerFormPage/>}/><Route path="customers/:id" element={<CustomerDetailPage/>}/><Route path="customers/:id/edit" element={<CustomerFormPage/>}/><Route path="activities" element={<ActivitiesPage/>}/><Route path="activities/new/:type" element={<ActivityFormPage/>}/><Route path="activities/:id" element={<ActivityDetailPage/>}/><Route path="activities/:id/edit" element={<ActivityFormPage/>}/><Route path="follow-up" element={<FollowUpCenter/>}/><Route path="calendar" element={<CalendarPage/>}/><Route path="profile" element={<Profile/>}/><Route path="admin" element={protectedPage(<AdminPage/>, true)}/>
    <Route path="add" element={<CustomerFormPage/>}/><Route path="edit/:id" element={<CustomerFormPage/>}/><Route path="dashboard" element={<Navigate to="/customers" replace/>}/>
  </Route><Route path="*" element={<Navigate to="/" replace/>}/></Routes></Suspense></BrowserRouter></AuthProvider>;
}
